name: Makefile CI

on: [push]


jobs:
  build:
    name: Build and Refactor
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v4

    - name: ⚙️ Install uv
      uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4

    - name: 🧰 Run `make setup`
      run: make setup

    - name: 🧹 Run `make refactor`
      run: make refactor

    - name: 📁 List files in workspace
      run: ls -la "${{ github.workspace }}"
